### ISSUE TITLE
TODO: Debug memory usage of tests

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/judge-server#1149]
- [ ] Debug memory usage of `sandbox_nasm_kill_judge`
- [ ] Debug memory usage of `sandbox_nasm64_kill_judge`
- [ ] Debug why `c_failinit` is reporting MLE instead of `failed initializing`/`segmentation fault`.
